// Stub file for Convex API - will be generated by `npx convex dev`
export const api = {
  announcements: {
    list: "announcements:list",
    create: "announcements:create",
    update: "announcements:update",
    remove: "announcements:remove",
  },
  notifications: {
    list: "notifications:list",
    listLive: "notifications:listLive",
    create: "notifications:create",
    update: "notifications:update",
    remove: "notifications:remove",
  },
  aiSettings: {
    get: "aiSettings:get",
    update: "aiSettings:update",
    addKnowledge: "aiSettings:addKnowledge",
    removeKnowledge: "aiSettings:removeKnowledge",
  },
  chatSessions: {
    list: "chatSessions:list",
    create: "chatSessions:create",
    incrementMessageCount: "chatSessions:incrementMessageCount",
  },
  notificationMetrics: {
    get: "notificationMetrics:get",
    incrementView: "notificationMetrics:incrementView",
    incrementDismiss: "notificationMetrics:incrementDismiss",
  },
};
